//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caixa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public long id { get; set; }
        public double litros { get; set; }
        public long bomba_id { get; set; }
        public long preco_id { get; set; }
    
        public virtual Bomba Bomba { get; set; }
        public virtual Preco Preco { get; set; }
    }
}
